Repository InformedSolutions/JAQU-CAZ-Retrofit-UI, pull requests merged in 2020-03, with the labels that each got.

#95 [NT] Update puma version to fix vulnerability warning
  Gemfile.lock
  package.json
  yarn.lock
Labels: documentation

#97 [CAZB-639] Content change to Retrofit Cookie Policy
  Gemfile
  Gemfile.lock
  app/controllers/accessibility_statement_controller.rb
  app/controllers/application_controller.rb
  app/controllers/cookies_controller.rb
  app/views/accessibility_statement/index.html.haml
  app/views/cookies/_cookie_control.html.haml
  app/views/cookies/_ga.html.haml
  app/views/cookies/_session.html.haml
  app/views/cookies/index.html.haml
  app/views/layouts/_cookie_control.html.erb
  config/application.rb
  spec/api_wrappers/register_checker_api_spec.rb
Labels: documentation

#98 [CAZB-740] Hide Control Cookie buttons and add `Save and close` button
  app/views/layouts/_cookie_control.html.erb
Labels: documentation

#99 [NT] Fix Cookie Control black button
  app/javascript/packs/application.js
  app/javascript/src/cookieControl.js
Labels: bug

#106 [NT] Allow load custom loader class in production mode
  config/application.rb
  lib/custom_logger.rb
Labels: bug

#105 Promote Release v1.1.0 to pre-production
  .drone.yml
  .env.example
  .env.test
  .rubocop.yml
  Dockerfile.build
  Dockerfile.test
  Gemfile
  Gemfile.lock
  app/api_wrappers/register_checker_api.rb
  app/assets/stylesheets/application.css
  app/controllers/accessibility_statement_controller.rb
  app/controllers/application_controller.rb
  app/controllers/cookies_controller.rb
  app/javascript/packs/application.js
  app/javascript/packs/google_analytics.js
  app/javascript/src/cookieControl.js
  app/javascript/styles/application.scss
  app/javascript/styles/cookie_control.scss
  app/mailers/upload_mailer.rb
  app/services/cognito/auth_user.rb
  app/services/cognito/confirm_forgot_password.rb
  app/services/cognito/forgot_password.rb
  app/services/cognito/get_user.rb
  app/services/cognito/respond_to_auth_challenge.rb
  app/services/csv_upload_service.rb
  app/services/email_validator.rb
  app/views/accessibility_statement/index.html.haml
  app/views/cookies/_cookie_control.html.haml
  app/views/cookies/_ga.html.haml
  app/views/cookies/_seen_message.html.haml
  app/views/cookies/_session.html.haml
  app/views/cookies/index.html.haml
  app/views/layouts/_cookie_control.html.erb
  app/views/layouts/_cookies_banner.haml
  app/views/layouts/_google_analytics.html.erb
  app/views/layouts/application.html.haml
  app/views/upload/data_rules.html.haml
  config/application.rb
  config/initializers/amazon_s3.rb
  config/initializers/application_controller_renderer.rb
  config/initializers/content_security_policy.rb
  config/initializers/filter_parameter_logging.rb
  config/initializers/remote_authenticatable.rb
  features/step_definitions/upload_steps.rb
  package.json
  sonar-project.properties
  spec/api_wrappers/register_checker_api_spec.rb
  spec/fixtures/files/csv/CAZ-2020-01-08.CSV
  spec/fixtures/files/csv/CAZ-2020-01-08.csv
  spec/fixtures/files/csv/empty/CAZ-2020-01-08.xlsx
  spec/fixtures/files/csv/empty/CAZ-2020-01.csv
  spec/mailers/previews/upload_mailer_preview.rb
  spec/mailers/upload_mailer_spec.rb
  spec/requests/sign_in_spec.rb
  spec/requests/upload_spec.rb
  spec/services/cognito/auth_user_spec.rb
  spec/services/csv_upload_service_spec.rb
  spec/services/ses/send_success_email_spec.rb
  yarn.lock
Labels: release, v1.1.0

#108 Release v1.1.0 to Production
  .drone.yml
  .env.example
  .env.test
  .rubocop.yml
  Dockerfile.build
  Dockerfile.test
  Gemfile
  Gemfile.lock
  app/api_wrappers/register_checker_api.rb
  app/assets/stylesheets/application.css
  app/controllers/accessibility_statement_controller.rb
  app/controllers/application_controller.rb
  app/controllers/cookies_controller.rb
  app/javascript/packs/application.js
  app/javascript/packs/google_analytics.js
  app/javascript/src/cookieControl.js
  app/javascript/styles/application.scss
  app/javascript/styles/cookie_control.scss
  app/mailers/upload_mailer.rb
  app/services/cognito/auth_user.rb
  app/services/cognito/confirm_forgot_password.rb
  app/services/cognito/forgot_password.rb
  app/services/cognito/get_user.rb
  app/services/cognito/respond_to_auth_challenge.rb
  app/services/csv_upload_service.rb
  app/services/email_validator.rb
  app/views/accessibility_statement/index.html.haml
  app/views/cookies/_cookie_control.html.haml
  app/views/cookies/_ga.html.haml
  app/views/cookies/_seen_message.html.haml
  app/views/cookies/_session.html.haml
  app/views/cookies/index.html.haml
  app/views/layouts/_cookie_control.html.erb
  app/views/layouts/_cookies_banner.haml
  app/views/layouts/_google_analytics.html.erb
  app/views/layouts/application.html.haml
  app/views/upload/data_rules.html.haml
  config/application.rb
  config/initializers/amazon_s3.rb
  config/initializers/application_controller_renderer.rb
  config/initializers/content_security_policy.rb
  config/initializers/filter_parameter_logging.rb
  config/initializers/remote_authenticatable.rb
  features/step_definitions/upload_steps.rb
  package.json
  sonar-project.properties
  spec/api_wrappers/register_checker_api_spec.rb
  spec/fixtures/files/csv/CAZ-2020-01-08.CSV
  spec/fixtures/files/csv/CAZ-2020-01-08.csv
  spec/fixtures/files/csv/empty/CAZ-2020-01-08.xlsx
  spec/fixtures/files/csv/empty/CAZ-2020-01.csv
  spec/mailers/previews/upload_mailer_preview.rb
  spec/mailers/upload_mailer_spec.rb
  spec/requests/sign_in_spec.rb
  spec/requests/upload_spec.rb
  spec/services/cognito/auth_user_spec.rb
  spec/services/csv_upload_service_spec.rb
  spec/services/ses/send_success_email_spec.rb
  yarn.lock
Labels: release, v1.1.0

#110 Update production URL for ecs checks
  .drone.yml
Labels: release, v1.1.0
