Repository InformedSolutions/JAQU-CAZ-Retrofit-UI, pull requests merged in 2020-07, with the labels that each got.

#175 [CAZB-1908] Error message changes
  app/controllers/sessions_controller.rb
  app/views/devise/sessions/new.html.haml
  config/locales/devise.en.yml
  config/locales/en.yml
  config/routes.rb
  features/password_reset.feature
  features/sign_in.feature
  features/step_definitions/force_password_change_steps.rb
  features/upload.feature
  lib/authentication_strategies/remote.rb
  spec/requests/sign_in_spec.rb
Labels: documentation

#186 Promote Retrofit v1.3.0 to Pre-Production
  .drone.yml
  .env.test
  .rubocop.yml
  .ruby-version
  Dockerfile.build
  Dockerfile.test
  Gemfile
  Gemfile.lock
  README.md
  app/controllers/passwords_controller.rb
  app/helpers/application_helper.rb
  app/javascript/styles/cookie_control.scss
  app/services/cognito/cognito_base_service.rb
  app/services/cognito/confirm_forgot_password.rb
  app/services/cognito/forgot_password.rb
  app/services/cognito/forgot_password/confirm.rb
  app/services/cognito/forgot_password/get_user.rb
  app/services/cognito/forgot_password/rate_limit_verification.rb
  app/services/cognito/forgot_password/reset.rb
  app/services/cognito/forgot_password/update_user.rb
  app/views/accessibility_statement/index.html.haml
  app/views/cookies/_ga.html.haml
  app/views/cookies/index.html.haml
  app/views/layouts/_cookie_control.html.erb
  app/views/layouts/_feedback_section.html.haml
  app/views/layouts/_header.html.haml
  app/views/layouts/application.html.haml
  app/views/passwords/success.html.haml
  app/views/upload/processing.html.haml
  app/views/upload/success.html.haml
  build_utils/check_build_number.sh
  config/environments/development.rb
  config/initializers/amazon_s3.rb
  config/initializers/aws_ses.rb
  config/initializers/backtrace_silencers.rb
  config/initializers/inflections.rb
  config/initializers/mime_types.rb
  config/initializers/null_db_adapter_monkey_patches.rb
  config/locales/en.yml
  features/step_definitions/password_reset_steps.rb
  features/step_definitions/upload_steps.rb
  package.json
  spec/requests/passwords/change_spec.rb
  spec/requests/passwords/send_confirmation_code_spec.rb
  spec/services/cognito/forgot_password/confirm_spec.rb
  spec/services/cognito/forgot_password/get_user_spec.rb
  spec/services/cognito/forgot_password/rate_limit_verification_spec.rb
  spec/services/cognito/forgot_password/reset_spec.rb
  spec/services/cognito/forgot_password/update_user_spec.rb
  yarn.lock
Labels: Retro v1.3.0, release

#189 Promote Retro 1.3.0 to Production
  .drone.yml
  .env.test
  .rubocop.yml
  .ruby-version
  Dockerfile.build
  Dockerfile.test
  Gemfile
  Gemfile.lock
  README.md
  app/controllers/passwords_controller.rb
  app/helpers/application_helper.rb
  app/javascript/styles/cookie_control.scss
  app/services/cognito/cognito_base_service.rb
  app/services/cognito/confirm_forgot_password.rb
  app/services/cognito/forgot_password.rb
  app/services/cognito/forgot_password/confirm.rb
  app/services/cognito/forgot_password/get_user.rb
  app/services/cognito/forgot_password/rate_limit_verification.rb
  app/services/cognito/forgot_password/reset.rb
  app/services/cognito/forgot_password/update_user.rb
  app/views/accessibility_statement/index.html.haml
  app/views/cookies/_ga.html.haml
  app/views/cookies/index.html.haml
  app/views/layouts/_cookie_control.html.erb
  app/views/layouts/_feedback_section.html.haml
  app/views/layouts/_header.html.haml
  app/views/layouts/application.html.haml
  app/views/passwords/success.html.haml
  app/views/upload/processing.html.haml
  app/views/upload/success.html.haml
  build_utils/check_build_number.sh
  config/environments/development.rb
  config/initializers/amazon_s3.rb
  config/initializers/aws_ses.rb
  config/initializers/backtrace_silencers.rb
  config/initializers/inflections.rb
  config/initializers/mime_types.rb
  config/initializers/null_db_adapter_monkey_patches.rb
  config/locales/en.yml
  features/step_definitions/password_reset_steps.rb
  features/step_definitions/upload_steps.rb
  package.json
  spec/requests/passwords/change_spec.rb
  spec/requests/passwords/send_confirmation_code_spec.rb
  spec/services/cognito/forgot_password/confirm_spec.rb
  spec/services/cognito/forgot_password/get_user_spec.rb
  spec/services/cognito/forgot_password/rate_limit_verification_spec.rb
  spec/services/cognito/forgot_password/reset_spec.rb
  spec/services/cognito/forgot_password/update_user_spec.rb
  yarn.lock
Labels: Retro v1.3.0, do not merge, release
