Repository InformedSolutions/JAQU-CAZ-Retrofit-UI, pull requests merged in 2020-01, with the labels that each got.

#72 Promote Release/v1.0.0 to Pre-production
  .drone.yml
  .github/PULL_REQUEST_TEMPLATE
  .rubocop.yml
  .ruby-version
  .scss-lint.yml
  Dockerfile.build
  Dockerfile.test
  Gemfile
  Gemfile.lock
  README.md
  app/controllers/application_controller.rb
  app/javascript/src/cookiesBanner/styles.scss
  app/javascript/styles/application.scss
  app/mailers/upload_mailer.rb
  app/models/user.rb
  app/services/cognito/auth_user.rb
  app/services/cognito/respond_to_auth_challenge.rb
  app/views/cookies/_ga.html.haml
  app/views/cookies/_seen_message.html.haml
  app/views/cookies/_session.html.haml
  app/views/cookies/_table_head.html.haml
  app/views/cookies/index.html.haml
  config/environments/development.rb
  config/initializers/filter_parameter_logging.rb
  config/initializers/remote_authenticatable.rb
  config/initializers/session_store.rb
  features/cookies.feature
  features/step_definitions/helper_steps.rb
  features/step_definitions/sign_in_steps.rb
  features/step_definitions/upload_steps.rb
  features/support/login_helpers.rb
  features/upload.feature
  lib/authentication_strategies/remote.rb
  lib/rubocop/blacklist.yml
  package.json
  spec/rails_helper.rb
  spec/requests/sign_in_spec.rb
  spec/requests/upload_spec.rb
  spec/services/cognito/auth_user_spec.rb
  spec/services/cognito/get_user_spec.rb
  spec/support/mock_user.rb
  yarn.lock
Labels: release, v1.0.0

#76 Promote Release v1.0.0 to Production
  .drone.yml
  .github/PULL_REQUEST_TEMPLATE
  .rubocop.yml
  .ruby-version
  .scss-lint.yml
  Dockerfile.build
  Dockerfile.test
  Gemfile
  Gemfile.lock
  README.md
  app/controllers/application_controller.rb
  app/javascript/src/cookiesBanner/styles.scss
  app/javascript/styles/application.scss
  app/mailers/upload_mailer.rb
  app/models/user.rb
  app/services/cognito/auth_user.rb
  app/services/cognito/respond_to_auth_challenge.rb
  app/views/cookies/_ga.html.haml
  app/views/cookies/_seen_message.html.haml
  app/views/cookies/_session.html.haml
  app/views/cookies/_table_head.html.haml
  app/views/cookies/index.html.haml
  config/environments/development.rb
  config/initializers/filter_parameter_logging.rb
  config/initializers/remote_authenticatable.rb
  config/initializers/session_store.rb
  features/cookies.feature
  features/step_definitions/helper_steps.rb
  features/step_definitions/sign_in_steps.rb
  features/step_definitions/upload_steps.rb
  features/support/login_helpers.rb
  features/upload.feature
  lib/authentication_strategies/remote.rb
  lib/rubocop/blacklist.yml
  package.json
  spec/rails_helper.rb
  spec/requests/sign_in_spec.rb
  spec/requests/upload_spec.rb
  spec/services/cognito/auth_user_spec.rb
  spec/services/cognito/get_user_spec.rb
  spec/support/mock_user.rb
  yarn.lock
Labels: release, v1.0.0

#78 [CAZB-343] Update accessibility statement content
  app/views/accessibility_statement/index.html.haml
  features/accessibility_statement.feature
Labels: bug

#82 [CAZB-343] Update accessibility page
  app/views/accessibility_statement/index.html.haml
Labels: bug

#80 [NT] Update drone yml
  .drone.yml
Labels: enhancement

#84 Promotion of WCAG statement typo correction in SIT under release/v1.0.1
  .drone.yml
  app/views/accessibility_statement/index.html.haml
Labels: release, v1.0.1

#87 Add ST pipeline steps
  .drone.yml
Labels: enhancement
