Repository InformedSolutions/JAQU-CAZ-Retrofit-UI, pull requests merged in 2020-08, with the labels that each got.

#209 Promote AWS cutover
  .drone2.yml
  .env.test
  .rubocop.yml
  Dockerfile.build
  Dockerfile.test
  Gemfile
  Gemfile.lock
  Makefile
  app/controllers/upload_controller.rb
  app/services/cognito/auth_user.rb
  app/services/cognito/client.rb
  app/services/cognito/cognito_base_service.rb
  app/services/cognito/forgot_password/confirm.rb
  app/services/cognito/forgot_password/get_user.rb
  app/services/cognito/forgot_password/reset.rb
  app/services/cognito/forgot_password/update_user.rb
  app/services/cognito/get_user.rb
  app/services/cognito/respond_to_auth_challenge.rb
  config/initializers/amazon_s3.rb
  config/initializers/aws_ses.rb
  config/initializers/cognito_client.rb
  lib/authentication_strategies/remote.rb
  spec/requests/passwords/send_confirmation_code_spec.rb
  spec/services/cognito/auth_user_spec.rb
  spec/services/cognito/client_spec.rb
  spec/services/cognito/forgot_password/confirm_spec.rb
  spec/services/cognito/forgot_password/get_user_spec.rb
  spec/services/cognito/forgot_password/rate_limit_verification_spec.rb
  spec/services/cognito/forgot_password/reset_spec.rb
  spec/services/cognito/forgot_password/update_user_spec.rb
  spec/services/cognito/get_user_spec.rb
  spec/services/cognito/respond_to_auth_spec.rb
Labels: dont merge yet

#211 [CAZB-2533] Fix Spelling mistake on Data Rules page
  .drone.yml
  .drone2.yml
  .env.test
  .rubocop.yml
  Gemfile.lock
  app/controllers/application_controller.rb
  app/services/cognito/auth_user.rb
  app/services/cognito/get_user.rb
  app/services/cognito/respond_to_auth_challenge.rb
  app/services/csv_upload_service.rb
  app/services/ses/send_success_email.rb
  app/views/upload/data_rules.html.haml
  config/initializers/amazon_s3.rb
  config/initializers/null_db_adapter_monkey_patches.rb
  lib/assets/.keep
  package.json
  sonar-project.properties
  yarn.lock
Labels: bug

#213 [CAZB-2334] Configurable CSV size limit
  .env.example
  .env.test
  app/controllers/accessibility_statement_controller.rb
  app/controllers/concerns/.keep
  app/controllers/cookies_controller.rb
  app/controllers/static_pages_controller.rb
  app/services/csv_upload_service.rb
  app/views/layouts/_footer.html.haml
  app/views/static_pages/accessibility_statement.html.haml
  app/views/static_pages/cookies.html.haml
  app/views/static_pages/cookies/_cookie_control.html.haml
  app/views/static_pages/cookies/_ga.html.haml
  app/views/static_pages/cookies/_session.html.haml
  app/views/static_pages/cookies/_table_head.html.haml
  config/application.rb
  config/routes.rb
  features/step_definitions/upload_steps.rb
  features/upload.feature
  spec/api_wrappers/register_checker_api_spec.rb
  spec/requests/accessibility_statement_spec.rb
  spec/requests/cookies_spec.rb
  spec/requests/passwords/change_spec.rb
  spec/requests/passwords/confirm_reset_spec.rb
  spec/requests/passwords/create_spec.rb
  spec/requests/passwords/new_spec.rb
  spec/requests/passwords/reset_spec.rb
  spec/requests/passwords/send_confirmation_code_spec.rb
  spec/requests/passwords/success_spec.rb
  spec/requests/sign_in_spec.rb
  spec/requests/static_pages_spec.rb
  spec/requests/upload_spec.rb
  spec/services/csv_upload_service_spec.rb
Labels: documentation

#216 [CAZB-54] Set cache-control to no-store to prevent session reload
  config/environments/production.rb
Labels: bug

#237 [CAZB-2327] Update password policy
  .drone2.yml
  .rubocop.yml
  Gemfile.lock
  app/api_wrappers/register_checker_api.rb
  app/services/cognito/auth_user.rb
  app/services/cognito/respond_to_auth_challenge.rb
  app/views/passwords/_errored_field.html.haml
  config/environments/production.rb
  config/initializers/null_db_adapter_monkey_patches.rb
  config/locales/en.yml
  features/force_password_change.feature
  features/password_reset.feature
  features/step_definitions/force_password_change_steps.rb
  features/step_definitions/helper_steps.rb
  features/step_definitions/password_reset_steps.rb
  package.json
  yarn.lock
Labels: bug
