Repository InformedSolutions/JAQU-CAZ-Retrofit-UI, pull requests merged in 2021-02, with the labels that each got.

#332 [CAZB-4063] Migrate pipeline to Terraform v0.12.23
  .drone.yml
  .drone2.yml
Labels: bug

#333 Promote release v1.8.1 to pre-production
  .drone.yml
  .drone2.yml
Labels: release, release/v1.8.1

#336 Promote Retrofit v1.8.1 to Production
  .drone.yml
  .drone2.yml
Labels: Retro v1.8.1, release
